name: Random Discord Message

on:
  schedule:
    - cron: '20 19 * * *'
    - cron: '50 19 * * *'
    - cron: '15 20 * * *'
    - cron: '40 20 * * *'
    - cron: '10 21 * * *'
    - cron: '30 21 * * *'
  workflow_dispatch:

jobs:
  send-message:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install --no-cache-dir requests

      - name: Run script with random delay and chance
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: python random_message.py
