name: Random Discord Message

on:
  schedule:
    - cron: '0 * * * *'  # Chaque heure
  workflow_dispatch:      # Lancement manuel possible

jobs:
  send-message:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Run script with random delay and chance
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: python random_message.py
