name: Random Discord Message

on:
  schedule:
    - cron: '37 13 * * *'
    - cron: '41 13 * * *'
    - cron: '49 13 * * *'
    - cron: '28 13 * * *'
    - cron: '32 13 * * *'
    - cron: '53 13 * * *'
  workflow_dispatch:

jobs:
  send-message:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Run script with random delay and chance
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: python random_message.py
