name: Send Random Discord Message

on:
  schedule:
    - cron: '37 8 * * *'
    - cron: '14 11 * * *'
    - cron: '49 13 * * *'
    - cron: '22 16 * * *'
    - cron: '07 19 * * *'
    - cron: '53 21 * * *'
  workflow_dispatch:  # Permet aussi de le lancer manuellement

jobs:
  send-message:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Run script
        run: python random_message.py
