name: Envoyer message Discord

on:
  schedule:
    - cron: '0 8 * * *'   # 10h (UTC +2)
    - cron: '0 20 * * *'  # 22h (UTC +2)
  workflow_dispatch:      # Permet un lancement manuel

jobs:
  send-discord-message:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install requests
        run: pip install requests

      - name: Run script
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: python send_message.py
